; PlatformIO — Arduino Mega 2560 + JM-101B + SG90
; Téléversement : Ctrl+Shift+B  ou  pio run -t upload
; Moniteur série : pio device monitor

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library
    arduino-libraries/Servo
